### ISSUE TITLE
fatal error:rjmcmc/mpp/rectiliner_search.hpp:No such file or directory

### ISSUE THREAD

**Issue by shellwjl** [IGNF/librjmcmc#1]
When I add the building_footprint_extraction_gui.cpp to a new  empty wxWidgets project ,and  build this project ,then I get this error.
I opened the file "rjmcmc/mpp/",only found "configuration"  "energy" "kernel" and "direct_sampler.hpp"
IDE:C::B,  ubuntu
![2015-09-24 17 40 47](https://cloud.githubusercontent.com/assets/13949779/10070184/6a72998e-62e3-11e5-974f-0ef95fa9386f.png)

**Comment by mbredif** [comment]
Dear librjmcmc user,

building_footprint_extraction is sadly obsolete and should be removed from
the repository. Please use building_footprint_rectangle for an up to date
sample application.

By the way, could you tell me more about your project? I am very interested
in how the library is being used and in which context!

Cordially
Le 24 sept. 2015 11:39 AM, "Suede323324" notifications@github.com a
écrit :

**Comment by shellwjl** [comment]
Thanks mbredif! I use this library to extract road from Urban Aerial Images.I should  redefinite Energy and MPP......

**Comment by mbredif** [comment]
Great. Is it an open source project?
Le 24 sept. 2015 11:56 AM, "Suede323324" notifications@github.com a
écrit :

**Comment by shellwjl** [comment]
My tutor's project  cooperated with a japanese company.this is a small part of it.So I  think it could not be an open source project!

**Comment by julienperret** [comment]
Can I consider this issue closed?
Should we remove the deprecated sample from the repository until we have the time to rewrite it?
Julien

**Comment by mbredif** [comment]
Sure, go ahead !

## 

Mathieu Brédif
IGN - Institut National de l'Information Géographique et Forestière
Laboratoire MATIS
73 avenue de Paris 94165 Saint-Mandé
recherche.ign.fr/labos/matis/~bredif
Tel: +33 (0)1 43 98 83 19
