### ISSUE TITLE
how to use the sample?

### ISSUE THREAD

**Issue by magicsong** [IGNF/librjmcmc#2]
im new to linux,i just want to know how to run the code in sample?

**Comment by julienperret** [comment]
Hello,

this is a standard cmake project. You can easily find documentation on how to build a cmake project online.
The most common procedure would be something like:
go to the librjmcmc directory
julien@work:~$ cd librjmcmc
julien@work:~/librjmcmc$

create a directory to build the project and move into it:
julien@work:~/librjmcmc$ mkdir build
julien@work:~/librjmcmc$ cd build
julien@work:~/librjmcmc/build$

use cmake and make to build the project:
julien@work:~/librjmcmc/build$ cmake..
julien@work:~/librjmcmc/build$ make

you should new have the samples built. For instance, you can run the quickstart with:
julien@work:~/librjmcmc/build$ cd samples/quickstart
julien@work:~/librjmcmc/build/samples/quickstart$ ./quickstart

Hope that helps.
Julien

**Comment by magicsong** [comment]
Thanks julienprrret! I can run the quickstart on Code::Block successfully.Is the GUI project also a cmake project?I should build it like quickStart?Thank you very mach!
![screenshot_bfr_gui](https://cloud.githubusercontent.com/assets/4010679/10103412/5ae4dcf4-63d6-11e5-9c43-763ed227da46.png)

**Comment by shutian1986** [comment]
my computer is Window7,so can i run it in window7? Thank you very much!

**Comment by julienperret** [comment]
Hi,

CMake is also available on windows here: https://cmake.org/download/

After that, depending on the samples you want to try, you will need other dependencies such as :
    - xsltproc
    - libxerces-c-dev
    - doxygen
    - xsdcxx
    - libjpeg-dev
    - zlib1g-dev
    - libpng++-dev
    - libwxbase2.8-dev
    - libwxgtk2.8-dev
    - libtiff-dev
    - boost-dev
    - gilviewer

Never tried to build the library with windows so let us know how it goes.
