### ISSUE TITLE
where is GUI program entry point? 

### ISSUE THREAD

**Issue by shellwjl** [IGNF/librjmcmc#3]
I have built  this program sucessfully.However,where is GUI program entry point?I'm a green hand in linux.
this is build folder.
![2015-12-24 15 14 16](https://cloud.githubusercontent.com/assets/13949779/11991104/399cce5a-aa51-11e5-8586-36c2ec31eaa6.png)
and sample folder

![2015-12-24 15 16 49](https://cloud.githubusercontent.com/assets/13949779/11991117/5f2443c4-aa51-11e5-919a-d96b28dcdb0f.png)

cmake : 
![2015-12-24 16 26 06](https://cloud.githubusercontent.com/assets/13949779/11991972/3a76cce0-aa5b-11e5-970d-885b5d1e768b.png)
make:
![2015-12-24 16 28 03](https://cloud.githubusercontent.com/assets/13949779/11991981/56700eac-aa5b-11e5-9aaa-966677b629d0.png)

**Comment by julienperret** [comment]
Hi,

as you can see in the cmake warnings, the gui is disabled since you don't have wxfreechart.
Cmake does not tell you, however, that you also need the gilviewer extension. You can find it on github too (IGNF/gilviewer).
Once you've installed these, rerun cmake and the gui will be available.

Cheers

**Comment by Suede323324** [comment]
Sorry for the late reply.I have installed wxfreechart and gilviewer,but still not work.
![2015-12-26 01 05 40](https://cloud.githubusercontent.com/assets/13949779/12003890/f08fd5b4-ab6c-11e5-97e1-8a155900f663.png)

**Comment by shellwjl** [comment]
Sorry for the late reply.I have installed wxfreechart and gilviewer,but still not work.During compilation building_footprint_rectangle_cli(　ubuntu 15.04), I get following error:
/usr/bin/ld: CMakeFiles/building_footprint_rectangle_gui.dir/building_footprint_rectangle_gui.cpp.o: undefined reference to symbol 'XInitThreads'
/usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
samples/building_footprint_rectangle/gui/CMakeFiles/building_footprint_rectangle_gui.dir/build.make:105: recipe for target 'samples/building_footprint_rectangle/gui/building_footprint_rectangle_gui' failed
make[2]: **\* [samples/building_footprint_rectangle/gui/building_footprint_rectangle_gui] Error 1
CMakeFiles/Makefile2:542: recipe for target 'samples/building_footprint_rectangle/gui/CMakeFiles/building_footprint_rectangle_gui.dir/all' failed
make[1]: **\* [samples/building_footprint_rectangle/gui/CMakeFiles/building_footprint_rectangle_gui.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: **\* [all] Error 2

cmake:
![2015-12-26 01 07 29](https://cloud.githubusercontent.com/assets/13949779/12003913/1ceb05ce-ab6e-11e5-97b0-abf241e29c46.png)

**Comment by shellwjl** [comment]
Adding X11 to the line 11 of librjmcmc-master/samples/building_footprint_rectangle/gui/CMakeLists.txt.It works.
![2015-12-28 15 47 59](https://cloud.githubusercontent.com/assets/13949779/12015643/6776b6f2-ad7a-11e5-80ff-83c22d0f3506.png)
